theme: jekyll-theme-cayman

# Setup
title: IocServiceStack .Net
tagline: A multi-service and multi-level dependency injection .net framework
baseurl: ""
paginate: 1

# About/contact
author:
  name:       Rajeswara Rao Jinaga
  url:        ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
