theme: jekyll-theme-cayman
name:         
tagline:      A multi-service and multi-level dependency injection .net libraray
# Setup
title: IoCServiceStack .Net
tagline: A responsive theme for your project on GitHub Pages
baseurl: ""
paginate: 1

# About/contact
author:
  name:       Rajeswara Rao Jinaga
  url:        ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
